export const products = [
  {
    id: 'PCD_1',
    name: 'TRENZA DORADA',
    price: 5000,
    imageUrl: '/assets/products/PCD_1.jpg',
    category: 'cadenas',
    dimensions: '67X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_2',
    name: 'CUBAN LINK',
    price: 6000,
    imageUrl: '/assets/products/PCD_2.jpg',
    category: 'cadenas',
    dimensions: '65X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_3',
    name: 'ELITE CUBAN',
    price: 6000,
    imageUrl: '/assets/products/PCD_3.jpg',
    category: 'cadenas',
    dimensions: '44X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_4',
    name: 'CORTE BIZANTINA',
    price: 15000,
    imageUrl: '/assets/products/PCD_4.jpg',
    category: 'cadenas',
    dimensions: '61X1,3',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_5',
    name: 'MIAMI CUBAN LINK',
    price: 15000,
    imageUrl: '/assets/products/PCD_5.jpg',
    category: 'cadenas',
    dimensions: '58X1,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_6',
    name: 'GOLDEN ROPE',
    price: 5000,
    imageUrl: '/assets/products/PCD_6.jpg',
    category: 'cadenas',
    dimensions: '52X0,4',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_7',
    name: 'LINEA DORADA',
    price: 5000,
    imageUrl: '/assets/products/PCD_7.jpg',
    category: 'cadenas',
    dimensions: '51X0,2',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_8',
    name: 'CUBAN ICE DORADA',
    price: 15000,
    imageUrl: '/assets/products/PCD_8.jpg',
    category: 'cadenas',
    dimensions: '50X1,5',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_9',
    name: 'ICE PUNK ',
    price: 15000,
    imageUrl: '/assets/products/PCD_9.jpg',
    category: 'cadenas',
    dimensions: '50X2',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_10',
    name: 'ROYAL CUBAN',
    price: 15000,
    imageUrl: '/assets/products/PCD_10.jpg',
    category: 'cadenas',
    dimensions: '45,5X1,4',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_11',
    name: 'ESLABON REAL',
    price: 15000,
    imageUrl: '/assets/products/PCD_11.jpg',
    category: 'cadenas',
    dimensions: '50,5X1,3',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCD_12',
    name: 'CUBAN ICE SUPREME',
    price: 20000,
    imageUrl: '/assets/products/PCD_12.jpg',
    category: 'cadenas',
    dimensions: '49X2',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 0,
  },
  {
    id: 'PCM_1',
    name: 'DUO DE LUJO',
    price: 12000,
    imageUrl: '/assets/products/PCM_1.jpg',
    category: 'cadenas',
    dimensions: '53X1,2',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCN_1',
    name: 'ICE DARK',
    price: 15000,
    imageUrl: '/assets/products/PCN_1.jpg',
    category: 'cadenas',
    dimensions: '50X1,5',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_1',
    name: 'THE TOURBILLON',
    price: 10000,
    imageUrl: '/assets/products/PCP_1.jpg',
    category: 'cadenas',
    dimensions: '60X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PCP_2',
    name: 'CUBANA CLASSIC',
    price: 6000,
    imageUrl: '/assets/products/PCP_2.jpg',
    category: 'cadenas',
    dimensions: '58X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_3',
    name: 'URBAN LINK',
    price: 6000,
    imageUrl: '/assets/products/PCP_3.jpg',
    category: 'cadenas',
    dimensions: '53X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_4',
    name: 'LA FIX',
    price: 15000,
    imageUrl: '/assets/products/PCP_4.jpg',
    category: 'cadenas',
    dimensions: '58X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_5',
    name: 'ESLABONES CRUZADOS',
    price: 10000,
    imageUrl: '/assets/products/PCP_5.jpg',
    category: 'cadenas',
    dimensions: '63X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_6',
    name: 'ROLO STYLE',
    price: 5000,
    imageUrl: '/assets/products/PCP_6.jpg',
    category: 'cadenas',
    dimensions: '53X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_7',
    name: 'CORTE FIGARO',
    price: 5000,
    imageUrl: '/assets/products/PCP_7.jpg',
    category: 'cadenas',
    dimensions: '68X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_8',
    name: 'RECTANGULAR LINK',
    price: 5000,
    imageUrl: '/assets/products/PCP_8.jpg',
    category: 'cadenas',
    dimensions: '52X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_9',
    name: 'PLATEADA INDUSTRIAL',
    price: 5000,
    imageUrl: '/assets/products/PCP_9.jpg',
    category: 'cadenas',
    dimensions: '57X0,6',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_10',
    name: 'MIAMI CHAIN',
    price: 15000,
    imageUrl: '/assets/products/PCP_10.jpg',
    category: 'cadenas',
    dimensions: '58X1,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_11',
    name: 'ROPE STYLE',
    price: 5000,
    imageUrl: '/assets/products/PCP_11.jpg',
    category: 'cadenas',
    dimensions: '58X0,7',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_12',
    name: 'CORTE EXOTICO',
    price: 10000,
    imageUrl: '/assets/products/PCP_12.jpg',
    category: 'cadenas',
    dimensions: '58X1,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_13',
    name: 'CIRCULAR LINK',
    price: 5000,
    imageUrl: '/assets/products/PCP_13.jpg',
    category: 'cadenas',
    dimensions: '54X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_15',
    name: 'UNIQUE',
    price: 5000,
    imageUrl: '/assets/products/PCP_15.jpg',
    category: 'cadenas',
    dimensions: '54X0,4',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PCP_16',
    name: 'CUBANA STYLE',
    price: 6000,
    imageUrl: '/assets/products/PCP_16.jpg',
    category: 'cadenas',
    dimensions: '68X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_17',
    name: 'THE TOURBILLON',
    price: 5000,
    imageUrl: '/assets/products/PCP_17.jpg',
    category: 'cadenas',
    dimensions: '59X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_18',
    name: 'AMEN',
    price: 10000,
    imageUrl: '/assets/products/PCP_18.jpg',
    category: 'cadenas',
    dimensions: '59X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_19',
    name: 'THE TOURBILLON',
    price: 5000,
    imageUrl: '/assets/products/PCP_19.jpg',
    category: 'cadenas',
    dimensions: '67X0,6',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_20',
    name: 'BLOCK STYLE',
    price: 5000,
    imageUrl: '/assets/products/PCP_20.jpg',
    category: 'cadenas',
    dimensions: '55X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_21',
    name: 'THE TOURBILLON',
    price: 5000,
    imageUrl: '/assets/products/PCP_21.jpg',
    category: 'cadenas',
    dimensions: '67X0,7',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PCP_22',
    name: 'CORTE ICE',
    price: 15000,
    imageUrl: '/assets/products/PCP_22.jpg',
    category: 'cadenas',
    dimensions: '50X1,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_23',
    name: 'CORTE TENNIS',
    price: 10000,
    imageUrl: '/assets/products/PCP_23.jpg',
    category: 'cadenas',
    dimensions: '50X0,7',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_24',
    name: 'BUTTERFLY EFFECT',
    price: 17000,
    imageUrl: '/assets/products/PCP_24.jpg',
    category: 'cadenas',
    dimensions: '50,5X1,2',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_25',
    name: 'CORTECITO',
    price: 17000,
    imageUrl: '/assets/products/PCP_25.jpg',
    category: 'cadenas',
    dimensions: '50X2',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PCP_26',
    name: 'CORTE FIGARO',
    price: 6000,
    imageUrl: '/assets/products/PCP_26.jpg',
    category: 'cadenas',
    dimensions: '54X0,9',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_1',
    name: 'SILUETA SAGRADA',
    price: 5000,
    imageUrl: '/assets/products/PDD_1.jpg',
    category: 'dijes',
    dimensions: '5,8X3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_2',
    name: 'BALA FINA',
    price: 7000,
    imageUrl: '/assets/products/PDD_2.jpg',
    category: 'dijes',
    dimensions: '6,5X3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_3',
    name: 'CRUZ GOTIKA',
    price: 5000,
    imageUrl: '/assets/products/PDD_3.jpg',
    category: 'dijes',
    dimensions: '2,8X1,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_4',
    name: 'EL GUARDIAN',
    price: 5000,
    imageUrl: '/assets/products/PDD_4.jpg',
    category: 'dijes',
    dimensions: '2,5X2,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_5',
    name: 'REY DEL CIELO',
    price: 5000,
    imageUrl: '/assets/products/PDD_5.jpg',
    category: 'dijes',
    dimensions: '3,5X2,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_6',
    name: 'BUTTERFLY',
    price: 12000,
    imageUrl: '/assets/products/PDD_6.jpg',
    category: 'dijes',
    dimensions: '7X5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_7',
    name: 'T DE TRAPSTAR',
    price: 10000,
    imageUrl: '/assets/products/PDD_7.jpg',
    category: 'dijes',
    dimensions: '8X4,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_8',
    name: 'GOLDEN SNAKE',
    price: 10000,
    imageUrl: '/assets/products/PDD_8.jpg',
    category: 'dijes',
    dimensions: '7X3,6',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_9',
    name: 'GOLDEN ANKH',
    price: 10000,
    imageUrl: '/assets/products/PDD_9.jpg',
    category: 'dijes',
    dimensions: '8,2X5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_10',
    name: 'SANTO BRILLO',
    price: 10000,
    imageUrl: '/assets/products/PDD_10.jpg',
    category: 'dijes',
    dimensions: '8X5,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_11',
    name: 'GLORIA ETERNA',
    price: 10000,
    imageUrl: '/assets/products/PDD_11.jpg',
    category: 'dijes',
    dimensions: '6,5X4,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_12',
    name: 'GUARDIAN DORADO',
    price: 10000,
    imageUrl: '/assets/products/PDD_12.jpg',
    category: 'dijes',
    dimensions: '11X6,8',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_13',
    name: 'OJO DE PANTERA',
    price: 9000,
    imageUrl: '/assets/products/PDD_13.jpg',
    category: 'dijes',
    dimensions: '7X3,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_14',
    name: 'ROYAL LION',
    price: 7000,
    imageUrl: '/assets/products/PDD_14.jpg',
    category: 'dijes',
    dimensions: '3,7X3,7',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_15',
    name: 'KING',
    price: 7000,
    imageUrl: '/assets/products/PDD_15.jpg',
    category: 'dijes',
    dimensions: '5X4',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_16',
    name: 'PAZ DORADA',
    price: 9000,
    imageUrl: '/assets/products/PDD_16.jpg',
    category: 'dijes',
    dimensions: '3,3X5,2',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PDD_17',
    name: 'CORONA SUPREMA',
    price: 7000,
    imageUrl: '/assets/products/PDD_17.jpg',
    category: 'dijes',
    dimensions: '3X3,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_18',
    name: 'DAVID ICE',
    price: 9000,
    imageUrl: '/assets/products/PDD_18.jpg',
    category: 'dijes',
    dimensions: '3,5X3,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_19',
    name: 'GOLDEN DOLLAR',
    price: 7000,
    imageUrl: '/assets/products/PDD_19.jpg',
    category: 'dijes',
    dimensions: '4,3X4,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_20',
    name: 'AK-47',
    price: 7000,
    imageUrl: '/assets/products/PDD_20.jpg',
    category: 'dijes',
    dimensions: '6,5X2,8',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_21',
    name: 'GOLDEN ICE UZI',
    price: 9000,
    imageUrl: '/assets/products/PDD_21.jpg',
    category: 'dijes',
    dimensions: '5X4,7',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_22',
    name: 'REY DE LA LUZ',
    price: 5000,
    imageUrl: '/assets/products/PDD_22.jpg',
    category: 'dijes',
    dimensions: '6X4,3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_23',
    name: 'GOLDEN DAVID',
    price: 5000,
    imageUrl: '/assets/products/PDD_23.jpg',
    category: 'dijes',
    dimensions: '5X4,2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_24',
    name: 'OJO DE HORUS',
    price: 5000,
    imageUrl: '/assets/products/PDD_24.jpg',
    category: 'dijes',
    dimensions: '3,8X3,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_25',
    name: 'KILLER GOLD',
    price: 5000,
    imageUrl: '/assets/products/PDD_25.jpg',
    category: 'dijes',
    dimensions: '4,2X2',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDD_26',
    name: 'EQUILIBRIO DORADO',
    price: 9000,
    imageUrl: '/assets/products/PDD_26.jpg',
    category: 'dijes',
    dimensions: '3,8X3,8',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PDD_27',
    name: 'ANKH',
    price: 5000,
    imageUrl: '/assets/products/PDD_27.jpg',
    category: 'dijes',
    dimensions: '4,5X2,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDM_1',
    name: 'CRUZ DE LUZ',
    price: 5000,
    imageUrl: '/assets/products/PDM_1.jpg',
    category: 'dijes',
    dimensions: '4X3',
    materials: 'ACERO QUIRURJICO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDM_2',
    name: 'DIAMOND CROSS',
    price: 10000,
    imageUrl: '/assets/products/PDM_2.jpg',
    category: 'dijes',
    dimensions: '6X3,7',
    materials: 'ALEACION DE ZINC',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDM_3',
    name: 'ROYAL CROSS',
    price: 10000,
    imageUrl: '/assets/products/PDM_3.jpg',
    category: 'dijes',
    dimensions: '6X3,7',
    materials: 'ALEACION DE ZINC',
    color: 'Mixto',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_1',
    name: 'OJO DE FUEGO',
    price: 5000,
    imageUrl: '/assets/products/PDP_1.jpg',
    category: 'dijes',
    dimensions: '4,2X2,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_2',
    name: 'DARK SERPENT',
    price: 5000,
    imageUrl: '/assets/products/PDP_2.jpg',
    category: 'dijes',
    dimensions: '4,8X3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_3',
    name: 'VUELANDO ALTO',
    price: 5000,
    imageUrl: '/assets/products/PDP_3.jpg',
    category: 'dijes',
    dimensions: '4,1X3,6',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_4',
    name: 'FE DE ACERO',
    price: 5000,
    imageUrl: '/assets/products/PDP_4.jpg',
    category: 'dijes',
    dimensions: '5,3X3,3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_5',
    name: 'VERSA LION',
    price: 5000,
    imageUrl: '/assets/products/PDP_5.jpg',
    category: 'dijes',
    dimensions: '3,9X3,9',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_6',
    name: 'MEDUSA REAL',
    price: 5000,
    imageUrl: '/assets/products/PDP_6.jpg',
    category: 'dijes',
    dimensions: '4,3X4,3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_7',
    name: 'LUZ ETERNA',
    price: 5000,
    imageUrl: '/assets/products/PDP_7.jpg',
    category: 'dijes',
    dimensions: '5,5X3,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_8',
    name: 'SILVER DAVID',
    price: 5000,
    imageUrl: '/assets/products/PDP_8.jpg',
    category: 'dijes',
    dimensions: '5X4,2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_9',
    name: 'KILLER SILVER',
    price: 5000,
    imageUrl: '/assets/products/PDP_9.jpg',
    category: 'dijes',
    dimensions: '4,2X2,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_10',
    name: 'CRUZ CARBONO',
    price: 5000,
    imageUrl: '/assets/products/PDP_10.jpg',
    category: 'dijes',
    dimensions: '5,7X4,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PDP_11',
    name: 'BLACK PANTHER',
    price: 5000,
    imageUrl: '/assets/products/PDP_11.jpg',
    category: 'dijes',
    dimensions: '4,3X3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_12A',
    name: 'BIG TILLAS A',
    price: 9000,
    imageUrl: '/assets/products/PDP_12A.jpg',
    category: 'dijes',
    dimensions: '4X2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_12B',
    name: 'BIG TILLAS B',
    price: 9000,
    imageUrl: '/assets/products/PDP_12B.jpg',
    category: 'dijes',
    dimensions: '4X2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_13',
    name: 'THRASHER',
    price: 5000,
    imageUrl: '/assets/products/PDP_13.jpg',
    category: 'dijes',
    dimensions: '4,5X2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_14',
    name: 'DIVINA SALVACION',
    price: 10000,
    imageUrl: '/assets/products/PDP_14.jpg',
    category: 'dijes',
    dimensions: '6,5X4,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_15',
    name: 'SILVER ANKH',
    price: 10000,
    imageUrl: '/assets/products/PDP_15.jpg',
    category: 'dijes',
    dimensions: '8,2X5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
        stock: 1,
  },
  {
    id: 'PDP_16',
    name: 'GUARDIAN PLATEADO',
    price: 10000,
    imageUrl: '/assets/products/PDP_16.jpg',
    category: 'dijes',
    dimensions: '11X6,8',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_17',
    name: 'BIG BOSS',
    price: 12000,
    imageUrl: '/assets/products/PDP_17.jpg',
    category: 'dijes',
    dimensions: '6,5X6,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_18',
    name: 'ICE BALL',
    price: 9000,
    imageUrl: '/assets/products/PDP_18.jpg',
    category: 'dijes',
    dimensions: '2,5X2,5',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_19',
    name: 'SILVER SNAKE',
    price: 10000,
    imageUrl: '/assets/products/PDP_19.jpg',
    category: 'dijes',
    dimensions: '7X3,6',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PDP_20',
    name: 'SILVER ICE UZI',
    price: 10000,
    imageUrl: '/assets/products/PDP_20.jpg',
    category: 'dijes',
    dimensions: '5,2X4,7',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_1',
    name: 'INTENSO',
    price: 7000,
    imageUrl: '/assets/products/PPP_1.jpg',
    category: 'pulseras',
    dimensions: '19X2',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_2',
    name: 'CORTE CUBANO',
    price: 5000,
    imageUrl: '/assets/products/PPP_2.jpg',
    category: 'pulseras',
    dimensions: '20X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_3',
    name: 'COMPLEX',
    price: 5000,
    imageUrl: '/assets/products/PPP_3.jpg',
    category: 'pulseras',
    dimensions: '21X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_4',
    name: 'FORZADO',
    price: 5000,
    imageUrl: '/assets/products/PPP_4.jpg',
    category: 'pulseras',
    dimensions: '20X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 2,
  },
  {
    id: 'PPP_5',
    name: 'CORTE CELDAS',
    price: 5000,
    imageUrl: '/assets/products/PPP_5.jpg',
    category: 'pulseras',
    dimensions: '21X0,5',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_6',
    name: 'CIRCULAR STYLE',
    price: 5000,
    imageUrl: '/assets/products/PPP_6.jpg',
    category: 'pulseras',
    dimensions: '20X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_7',
    name: 'HEART',
    price: 10000,
    imageUrl: '/assets/products/PPP_7.jpg',
    category: 'pulseras',
    dimensions: '20X1',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPP_8',
    name: 'INTOCABLE',
    price: 10000,
    imageUrl: '/assets/products/PPP_8.jpg',
    category: 'pulseras',
    dimensions: '22X1,3',
    materials: 'ALEACION DE ZINC',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_1',
    name: 'INCA',
    price: 7000,
    imageUrl: '/assets/products/PPD_1.jpg',
    category: 'pulseras',
    dimensions: '22X1,3',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_2',
    name: 'SOMOS STAR',
    price: 5000,
    imageUrl: '/assets/products/PPD_2.jpg',
    category: 'pulseras',
    dimensions: '17X0,5',
    materials: 'BAÑADO EN ORO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_3',
    name: 'TRIDENTE',
    price: 5000,
    imageUrl: '/assets/products/PPD_3.jpg',
    category: 'pulseras',
    dimensions: '19X0,6',
    materials: 'BAÑADO EN ORO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_4',
    name: 'FIXA',
    price: 5000,
    imageUrl: '/assets/products/PPD_4.jpg',
    category: 'pulseras',
    dimensions: '18,5X1,7',
    materials: 'BAÑADO EN ORO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_5',
    name: 'CORTE RED',
    price: 5000,
    imageUrl: '/assets/products/PPD_5.jpg',
    category: 'pulseras',
    dimensions: '20X0,5',
    materials: 'BAÑADO EN ORO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPD_6',
    name: 'BLACK STYLE',
    price: 5000,
    imageUrl: '/assets/products/PPD_6.jpg',
    category: 'pulseras',
    dimensions: '21X0,6',
    materials: 'BAÑADO EN ORO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPM_1',
    name: 'CORTE MIX',
    price: 5000,
    imageUrl: '/assets/products/PPM_1.jpg',
    category: 'pulseras',
    dimensions: '19X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPM_2',
    name: 'INCA MIX',
    price: 5000,
    imageUrl: '/assets/products/PPM_2.jpg',
    category: 'pulseras',
    dimensions: '19X0,8',
    materials: 'ACERO QUIRURJICO',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PPN_1',
    name: 'BLACK LINK',
    price: 5000,
    imageUrl: '/assets/products/PPN_1.jpg',
    category: 'pulseras',
    dimensions: '19X1',
    materials: 'ACERO QUIRURJICO',
    color: 'Negro',
    detail: '',
    stock: 1,
  },
  {
    id: 'PAX_1',
    name: 'BOX RINGS',
    price: 5000,
    imageUrl: '/assets/products/PAX_1.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'BAÑADO EN PLATA',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PAX_2',
    name: 'HEARTS RINGS',
    price: 5000,
    imageUrl: '/assets/products/PAX_2.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'BAÑADO EN PLATA',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PAX_3',
    name: 'CORTE RINGS',
    price: 5000,
    imageUrl: '/assets/products/PAX_3.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'BAÑADO EN PLATA',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PAX_4',
    name: 'ICE RINGS',
    price: 8000,
    imageUrl: '/assets/products/PAX_4.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'BAÑADO EN PLATA',
    color: 'Plateado',
    detail: '',
    stock: 1,
  },
  {
    id: 'PAX_5',
    name: 'FIXONA',
    price: 5000,
    imageUrl: '/assets/products/PAX_5.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra ROJA',
    stock: 1,
  },
  {
    id: 'PAX_6',
    name: 'CUT',
    price: 5000,
    imageUrl: '/assets/products/PAX_6.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra NEGRA',
    stock: 1,
  },
  {
    id: 'PAX_7',
    name: 'LUJO',
    price: 5000,
    imageUrl: '/assets/products/PAX_7.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra NEGRA',
    stock: 1,
  },
  {
    id: 'PAX_8',
    name: 'FLOR',
    price: 5000,
    imageUrl: '/assets/products/PAX_8.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra ROSADA',
    stock: 1,
  },
  {
    id: 'PAX_9',
    name: 'CORONA',
    price: 5000,
    imageUrl: '/assets/products/PAX_9.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra AZUL',
    stock: 1,
  },
  {
    id: 'PAX_10',
    name: 'GREEN',
    price: 5000,
    imageUrl: '/assets/products/PAX_10.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra VERDE',
    stock: 1,
  },
  {
    id: 'PAX_11',
    name: 'PASION',
    price: 5000,
    imageUrl: '/assets/products/PAX_11.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra ROJA',
    stock: 1,
  },
  {
    id: 'PAX_12',
    name: 'PINK',
    price: 5000,
    imageUrl: '/assets/products/PAX_12.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra ROSADA',
    stock: 1,
  },
  {
    id: 'PAX_13',
    name: 'FLOWER',
    price: 5000,
    imageUrl: '/assets/products/PAX_13.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra NEGRA',
    stock: 1,
  },
  {
    id: 'PAX_14',
    name: 'DARK EYES',
    price: 5000,
    imageUrl: '/assets/products/PAX_14.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra NEGRA',
    stock: 1,
  },
  {
    id: 'PAX_15',
    name: 'GREEN STYLE',
    price: 5000,
    imageUrl: '/assets/products/PAX_15.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra VERDE',
    stock: 1,
  },
  {
    id: 'PAX_16',
    name: 'BLUE STAR',
    price: 5000,
    imageUrl: '/assets/products/PAX_16.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra AZUL',
    stock: 1,
  },
  {
    id: 'PAX_17',
    name: 'CRYSTAL CLEAR',
    price: 5000,
    imageUrl: '/assets/products/PAX_17.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'bañado en plata',
    color: 'Plateado',
    detail: 'PLATEADO con piedra TRANSPARENTE',
    stock: 1,
  },
  {
    id: 'PAX_18',
    name: 'GOLD TOUCH',
    price: 8000,
    imageUrl: '/assets/products/PAX_18.jpg',
    category: 'aros',
    dimensions: '',
    materials: 'BAÑADO EN ORO',
    color: 'Dorado',
    detail: '',
    stock: 1,
  },
];